#kubectl api-resources
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: shop-account-nginx
  ports:      
    - name: http
      port: 80
      nodePort: 30100
  type: LoadBalancer