#kubectl api-resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-account-nginx
  template:
    metadata:      
      labels:
        app: shop-account-nginx
    spec:
      containers:
        - name: site
          image: lauromiranda/shop-account          
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
              
---

apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: shop-account-nginx
  ports:      
    - name: http
      port: 80
      nodePort: 30100
  type: LoadBalancer